/**
 * Production columnDefs for gridDemo.
 *
 * Leading columns match the screenshot dashboard: ID, Customer, Status, Country,
 * Email, Balance, Created At, Progress, Rating, Actions — then extended
 * operational and financial fields (26 displayed columns total).
 */

import { COUNTRY_FLAG_SRC_MAP } from "./countryFlagMap.mjs";
import {
  COUNTRY_META,
  DEPARTMENTS,
  LANGUAGE_TONE_MAP,
  STATUSES,
  STATUS_TONE_MAP,
  TIERS,
  TIER_TONE_MAP,
} from "./demoConstants.mjs";

/** Synthetic row-number field — populated in transformRow. */
export const ROW_NUMBER_FIELD = "__rowNumber";

const COUNTRIES = Object.keys(COUNTRY_FLAG_SRC_MAP).sort();
const LANGUAGES = Object.keys(LANGUAGE_TONE_MAP).sort();
const REGIONS = [...new Set(Object.values(COUNTRY_META).map((m) => m.region))].sort();

const textFilter = { filter: "text", floatingFilter: true };
const numberFilter = { filter: "number", floatingFilter: true };
/** Narrow date columns: calendar button opens the dedicated filter panel.
 *  For inline start/end fields use `{ control: "dateRange" }` instead. */
const dateFilter = {
  filter: "date",
  floatingFilter: { control: "dateButton" },
};
const booleanFilter = { filter: "boolean", floatingFilter: true };

const selectFilter = (options) => ({
  filter: "text",
  floatingFilter: { control: "select", options },
});

const col = (def) => def;

/** @returns {unknown[]} */
export function buildGridDemoColumnDefs() {
  return [
    // ── Screenshot dashboard (leading columns) ─────────────────────────────
    col({
      field: ROW_NUMBER_FIELD,
      headerName: "ID",
      width: 72,
      pinned: "left",
      sortable: true,
      filter: false,
      floatingFilter: false,
      columnMenu: false,
      editable: false,
      resizable: false,
      reorderable: false,
      pinnable: false,
      columnSelectable: false,
      suppressRowClickSelection: true,
      cellDataType: "number",
    }),
    col({
      field: "name",
      headerName: "Customer",
      width: 200,
      pinned: "left",
      sortable: true,
      ...textFilter,
      editable: false,
      resizable: true,
      reorderable: true,
      pinnable: true,
      tooltip: true,
      quickFilterTextField: "nameText",
      cellClass: "cell-customer",
      cellDataType: "text",
      cellShell: {
        kind: "avatarText",
        image: { src: { field: "avatar" }, alt: { field: "name" } },
        text: "formattedValue",
      },
    }),
    col({
      field: "status",
      headerName: "Status",
      width: 120,
      sortable: true,
      ...selectFilter(STATUSES),
      resizable: true,
      reorderable: true,
      cellClass: "v-align",
      cellDataType: "text",
      cellShell: {
        kind: "badge",
        dot: true,
        tone: {
          from: "value",
          map: STATUS_TONE_MAP,
          fallback: "neutral",
        },
      },
    }),
    col({
      field: "country",
      headerName: "Country",
      width: 150,
      sortable: true,
      ...selectFilter(COUNTRIES),
      resizable: true,
      reorderable: true,
      cellClass: ["country-cell", "v-align"],
      cellDataType: "text",
      cellShell: {
        kind: "imageText",
        image: {
          src: {
            from: "value",
            map: COUNTRY_FLAG_SRC_MAP,
            fallback: "",
          },
          alt: { field: "country" },
        },
      },
    }),
    col({
      field: "email",
      headerName: "Email",
      width: 220,
      sortable: true,
      ...textFilter,
      resizable: true,
      reorderable: true,
      cellDataType: "text",
      quickFilterTextField: "emailText",
    }),
    col({
      field: "bankBalance",
      headerName: "Balance",
      width: 130,
      sortable: true,
      ...numberFilter,
      resizable: true,
      reorderable: true,
      cellDataType: "currency",
      quickFilterTextField: "bankBalanceText",
      cellShell: {
        kind: "prefixSuffix",
        text: { field: "bankBalanceFormatted" },
      },
    }),
    col({
      field: "createdAt",
      headerName: "Created At",
      width: 130,
      sortable: true,
      ...dateFilter,
      resizable: true,
      reorderable: true,
      cellDataType: "date",
    }),
    col({
      field: "progressPct",
      headerName: "Progress",
      width: 140,
      sortable: true,
      ...numberFilter,
      resizable: true,
      reorderable: true,
      cellClass: "cell-progress",
      cellDataType: "number",
      quickFilterTextField: "progressText",
      cellShell: {
        kind: "progress",
      },
    }),
    col({
      field: "rating",
      headerName: "Rating",
      width: 110,
      sortable: true,
      ...numberFilter,
      resizable: true,
      reorderable: true,
      cellClass: "cell-rating",
      cellDataType: "number",
      quickFilterTextField: "ratingText",
      cellShell: {
        kind: "rating",
        icon: "★",
      },
    }),
    col({
      field: "customPanel",
      headerName: "",
      headerAriaLabel: "Customer details panel",
      width: 56,
      pinned: "right",
      cellKind: "actions",
      actionsKey: "customRowDropdown",
      columnMenu: false,
      filter: false,
      floatingFilter: false,
      sortable: false,
      editable: false,
      resizable: false,
      reorderable: false,
      pinnable: false,
      columnSelectable: false,
      suppressRowClickSelection: true,
      actionTrigger: {
        icon: "▣",
        ariaLabel: "Open custom row panel with links",
        placement: "left-center",
      },
    }),
    col({
      field: "actions",
      headerName: "",
      headerAriaLabel: "Row actions",
      width: 44,
      pinned: "right",
      cellKind: "actions",
      actionsKey: "rowActions",
      columnMenu: false,
      filter: false,
      floatingFilter: false,
      sortable: false,
      editable: false,
      resizable: false,
      reorderable: false,
      pinnable: false,
      columnSelectable: false,
      suppressRowClickSelection: true,
      actionTrigger: {
        icon: "⋯",
        ariaLabel: "Open row actions",
        placement: "left-center",
      },
    }),

    // ── Extended production columns (scroll horizontally) ──────────────────
    col({
      field: "department",
      headerName: "Department",
      width: 140,
      sortable: true,
      ...selectFilter(DEPARTMENTS),
      resizable: true,
      reorderable: true,
      cellDataType: "text",
    }),
    col({
      field: "jobTitle",
      headerName: "Job Title",
      width: 180,
      sortable: true,
      ...textFilter,
      resizable: true,
      reorderable: true,
      cellDataType: "text",
    }),
    col({
      field: "employeeCode",
      headerName: "Account ID",
      width: 130,
      sortable: true,
      ...textFilter,
      resizable: true,
      reorderable: true,
      cellDataType: "text",
    }),
    col({
      field: "city",
      headerName: "City",
      width: 130,
      sortable: true,
      ...textFilter,
      resizable: true,
      reorderable: true,
      cellDataType: "text",
    }),
    col({
      field: "region",
      headerName: "Region",
      width: 140,
      sortable: true,
      ...selectFilter(REGIONS),
      resizable: true,
      reorderable: true,
      cellDataType: "text",
    }),
    col({
      field: "language",
      headerName: "Language",
      width: 120,
      sortable: true,
      ...selectFilter(LANGUAGES),
      resizable: true,
      reorderable: true,
      cellDataType: "text",
      cellShell: {
        kind: "badge",
        dot: false,
        tone: {
          from: "value",
          map: LANGUAGE_TONE_MAP,
          fallback: "neutral",
        },
      },
    }),
    col({
      field: "tier",
      headerName: "Tier",
      width: 110,
      sortable: true,
      ...selectFilter(TIERS),
      resizable: true,
      reorderable: true,
      cellDataType: "text",
      cellShell: {
        kind: "badge",
        dot: true,
        tone: {
          from: "value",
          map: TIER_TONE_MAP,
          fallback: "neutral",
        },
      },
    }),
    col({
      field: "totalWinnings",
      headerName: "Lifetime Value",
      width: 150,
      sortable: true,
      ...numberFilter,
      resizable: true,
      reorderable: true,
      cellDataType: "currency",
      quickFilterTextField: "totalWinningsText",
      cellShell: {
        kind: "prefixSuffix",
        text: { field: "totalWinningsFormatted" },
      },
    }),
    col({
      field: "revenueYtd",
      headerName: "Revenue YTD",
      width: 140,
      sortable: true,
      ...numberFilter,
      resizable: true,
      reorderable: true,
      cellDataType: "currency",
      cellShell: {
        kind: "prefixSuffix",
        text: { field: "revenueYtdFormatted" },
      },
    }),
    col({
      field: "marginPct",
      headerName: "Margin %",
      width: 110,
      sortable: true,
      ...numberFilter,
      resizable: true,
      reorderable: true,
      cellDataType: "number",
      cellShell: {
        kind: "prefixSuffix",
        suffix: "%",
        text: "formattedValue",
      },
    }),
    col({
      field: "joinDate",
      headerName: "Join Date",
      width: 130,
      sortable: true,
      ...dateFilter,
      resizable: true,
      reorderable: true,
      cellDataType: "date",
    }),
    col({
      field: "lastActiveAt",
      headerName: "Last Active",
      width: 130,
      sortable: true,
      ...dateFilter,
      resizable: true,
      reorderable: true,
      cellDataType: "date",
    }),
    col({
      field: "game.name",
      headerName: "Product",
      width: 170,
      sortable: true,
      ...textFilter,
      resizable: true,
      reorderable: true,
      cellDataType: "text",
      quickFilterTextField: "gameNameText",
    }),
    col({
      field: "game.bought",
      headerName: "Purchased",
      width: 120,
      sortable: true,
      ...booleanFilter,
      resizable: true,
      reorderable: true,
      cellDataType: "boolean",
      quickFilterTextField: "boughtText",
      cellShell: {
        kind: "badge",
        dot: false,
        text: {
          from: "value",
          map: { true: "Yes", false: "No" },
        },
        tone: {
          from: "value",
          map: { true: "success", false: "inactive" },
          fallback: "neutral",
        },
      },
    }),
    col({
      field: "creditUsedPct",
      headerName: "Credit Used",
      width: 130,
      sortable: true,
      ...numberFilter,
      resizable: true,
      reorderable: true,
      cellDataType: "number",
      cellShell: {
        kind: "progress",
      },
    }),
  ];
}
